/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as HSlugSplatRouteImport } from './routes/h.$slug.$'
import { Route as ApiPublicV1DeployRouteImport } from './routes/api/public/v1/deploy'
import { Route as ApiPublicV1SitesRouteImport } from './routes/api/public/v1/sites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugSplatRoute = HSlugSplatRouteImport.update({
  id: '/h/$slug/$',
  path: '/h/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DeployRoute = ApiPublicV1DeployRouteImport.update({
  id: '/api/public/v1/deploy',
  path: '/api/public/v1/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SitesRoute = ApiPublicV1SitesRouteImport.update({
  id: '/api/public/v1/sites',
  path: '/api/public/v1/sites',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof PainelRoute
  '/servicos': typeof ServicosRoute
  '/h/$slug/$': typeof HSlugSplatRoute
  '/api/public/v1/deploy': typeof ApiPublicV1DeployRoute
  '/api/public/v1/sites': typeof ApiPublicV1SitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof PainelRoute
  '/servicos': typeof ServicosRoute
  '/h/$slug/$': typeof HSlugSplatRoute
  '/api/public/v1/deploy': typeof ApiPublicV1DeployRoute
  '/api/public/v1/sites': typeof ApiPublicV1SitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof PainelRoute
  '/servicos': typeof ServicosRoute
  '/h/$slug/$': typeof HSlugSplatRoute
  '/api/public/v1/deploy': typeof ApiPublicV1DeployRoute
  '/api/public/v1/sites': typeof ApiPublicV1SitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/servicos'
    | '/h/$slug/$'
    | '/api/public/v1/deploy'
    | '/api/public/v1/sites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/painel'
    | '/servicos'
    | '/h/$slug/$'
    | '/api/public/v1/deploy'
    | '/api/public/v1/sites'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/painel'
    | '/servicos'
    | '/h/$slug/$'
    | '/api/public/v1/deploy'
    | '/api/public/v1/sites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PainelRoute: typeof PainelRoute
  ServicosRoute: typeof ServicosRoute
  HSlugSplatRoute: typeof HSlugSplatRoute
  ApiPublicV1DeployRoute: typeof ApiPublicV1DeployRoute
  ApiPublicV1SitesRoute: typeof ApiPublicV1SitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug/$': {
      id: '/h/$slug/$'
      path: '/h/$slug/$'
      fullPath: '/h/$slug/$'
      preLoaderRoute: typeof HSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/deploy': {
      id: '/api/public/v1/deploy'
      path: '/api/public/v1/deploy'
      fullPath: '/api/public/v1/deploy'
      preLoaderRoute: typeof ApiPublicV1DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sites': {
      id: '/api/public/v1/sites'
      path: '/api/public/v1/sites'
      fullPath: '/api/public/v1/sites'
      preLoaderRoute: typeof ApiPublicV1SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PainelRoute: PainelRoute,
  ServicosRoute: ServicosRoute,
  HSlugSplatRoute: HSlugSplatRoute,
  ApiPublicV1DeployRoute: ApiPublicV1DeployRoute,
  ApiPublicV1SitesRoute: ApiPublicV1SitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
